//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Buy
    {
        [Key]
        public int EnrollId { get; set; }
        public Nullable<int> CourseId { get; set; }
        [Required]
        [Display(Name = "Course name")]
        public string CourseName { get; set; }
        [Required]
        [Display(Name = "Course Fee")]
        public Nullable<decimal> CourseFee { get; set; }
        [Required]
        [Display(Name = "Enroll Date")]
        public Nullable<System.DateTime> EnrollDate { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
